// This file is generated by Velite

import type config from '../velite.config.ts'

type Collections = typeof config.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]
